name: Build SummitOS (LineageOS A23xq)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    
    steps:
      - name: Free disk space
        run: |
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /opt/ghc
          sudo rm -rf /opt/hostedtoolcache/CodeQL
          sudo rm -rf /usr/local/lib/android
          sudo rm -rf /usr/share/swift
          sudo rm -rf /usr/local/.ghcup
          sudo rm -rf /usr/local/share/boost
          sudo rm -rf "$AGENT_TOOLSDIRECTORY"
          sudo docker image prune --all --force
          sudo apt-get clean
          df -h
          
      - name: Checkout device tree
        uses: actions/checkout@v4
        with:
          path: device_tree
        
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y bc bison build-essential ccache curl \
            flex g++-multilib gcc-multilib git gnupg gperf imagemagick \
            lib32ncurses5-dev lib32readline-dev lib32z1-dev liblz4-tool \
            libncurses5 libncurses5-dev libsdl1.2-dev libssl-dev \
            libxml2 libxml2-utils lzop pngcrush rsync schedtool \
            squashfs-tools xsltproc zip zlib1g-dev python3 openjdk-11-jdk \
            python-is-python3
          df -h
          
      - name: Setup repo tool
        run: |
          mkdir -p ~/bin
          curl https://storage.googleapis.com/git-repo-downloads/repo > ~/bin/repo
          chmod a+x ~/bin/repo
          echo "$HOME/bin" >> $GITHUB_PATH
          git config --global user.email "summitos@builder.com"
          git config --global user.name "SummitOS Builder"
          
      - name: Initialize minimal repo
        run: |
          mkdir -p ~/android/lineage
          cd ~/android/lineage
          ~/bin/repo init --depth=1 --no-repo-verify -u https://github.com/LineageOS/android.git -b lineage-23.0 --git-lfs
          df -h
          
      - name: Sync minimal source (this will take time and may fail)
        run: |
          cd ~/android/lineage
          ~/bin/repo sync -c --no-clone-bundle --no-tags --optimized-fetch --prune --force-sync -j$(nproc)
        continue-on-error: true
        
      - name: Check disk space
        run: |
          df -h
          du -sh ~/android/lineage
          
      - name: Copy device tree
        run: |
          mkdir -p ~/android/lineage/device/samsung
          cp -r $GITHUB_WORKSPACE/device_tree ~/android/lineage/device/samsung/a23xq
          ls -la ~/android/lineage/device/samsung/a23xq
          
      - name: Attempt build (will likely fail - device tree incomplete)
        run: |
          cd ~/android/lineage
          source build/envsetup.sh
          lunch lineage_a23xq-userdebug || echo "Lunch failed - expected"
          df -h
