name: Build SummitOS (LineageOS A23xq)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    timeout-minutes: 360  # 6 hours max
    
    steps:
      - name: Maximize build space
        run: |
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /opt/ghc
          sudo rm -rf /usr/local/share/boost
          sudo rm -rf "$AGENT_TOOLSDIRECTORY"
          sudo apt-get clean
          
      - name: Checkout device tree
        uses: actions/checkout@v4
        
      - name: Setup environment
        run: |
          sudo apt-get update
          sudo apt-get install -y bc bison build-essential ccache curl \
            flex g++-multilib gcc-multilib git gnupg gperf imagemagick \
            lib32ncurses5-dev lib32readline-dev lib32z1-dev liblz4-tool \
            libncurses5 libncurses5-dev libsdl1.2-dev libssl-dev \
            libxml2 libxml2-utils lzop pngcrush rsync schedtool \
            squashfs-tools xsltproc zip zlib1g-dev python3 openjdk-11-jdk
          
      - name: Setup repo
        run: |
          mkdir -p ~/bin
          curl https://storage.googleapis.com/git-repo-downloads/repo > ~/bin/repo
          chmod a+x ~/bin/repo
          echo "$HOME/bin" >> $GITHUB_PATH
          git config --global user.email "summitos@builder.com"
          git config --global user.name "SummitOS Builder"
          
      - name: Initialize repo
        run: |
          mkdir -p ~/lineage
          cd ~/lineage
          repo init -u https://github.com/LineageOS/android.git -b lineage-23.0 --depth=1
          
      - name: Sync (minimal)
        run: |
          cd ~/lineage
          repo sync -c -j4 --no-clone-bundle --no-tags
          
      - name: Copy device tree
        run: |
          mkdir -p ~/lineage/device/samsung
          cp -r $GITHUB_WORKSPACE ~/lineage/device/samsung/a23xq
          
      - name: Setup ccache
        run: |
          echo "export USE_CCACHE=1" >> ~/.bashrc
          echo "export CCACHE_EXEC=/usr/bin/ccache" >> ~/.bashrc
          ccache -M 5G
          
      - name: Build
        run: |
          cd ~/lineage
          source build/envsetup.sh
          lunch lineage_a23xq-userdebug
          mka bacon
          
      - name: Upload ROM
        uses: actions/upload-artifact@v4
        if: success()
        with:
          name: SummitOS-a23xq-${{ github.run_number }}
          path: ~/lineage/out/target/product/a23xq/lineage-*.zip
